name: Tutorial
version: ${project.version}
main: de.tischtiger.tutorial.Tutorial
api-version: 1.16

commands:
  heal:
    description: Heals the player
    usage: /<command>
    permission: tutorial.heal
    aliases:
      - hl

permissions:
  tutorial.heal:
    default: true
  tutorial.heal.other:
    default: op
